

--Business probelms 

--SHOW POSTS WITH HIGHEST ENGAGEMENT 

USE [LinkedIn_Growth_Analytics];
SELECT *, 
ROW_NUMBER () OVER ( ORDER BY likes DESC )AS ROWNUMER 
from [dbo].[posts];

--HIGH PERFORMING CREATORS ON BASIS OF LIKES

SELECT *, 
RANK() OVER ( ORDER BY likes DESC) AS RANKING
from [dbo].[posts];

--Dense rank creators
SELECT * ,
DENSE_RANK() OVER(ORDER BY likes DESC) AS DENE_RANKING
FROM [dbo].[posts];

--HOW MUCH OVERALL ENGAGEMENT A CREATOR HAS(LIKES,COMMNET,SHARES)

SELECT * ,
SUM(likes+comments+shares) OVER (PARTITION BY user_id  ) AS ENGENEMENT
FROM [dbo].[posts]
ORDER BY ENGENEMENT DESC;

--COMPARISON OF LIKES WITH LAST MONTH LIKES( ENGAGEMENT GROWTH)

SELECT *, 
LAG (likes) OVER ( PARTITION BY user_id ORDER BY post_date) AS last_month_likes
FROM [dbo].[posts];


--COMPARISON OF LIKES WITH NEXT MONTH LIKES( ENGAGEMENT GROWTH)

SELECT *,
LEAD(likes) OVER ( PARTITION BY user_id ORDER BY post_date) AS next_month_likes
FROM [dbo].[posts];


--COMPARIOSN OF GROWTH WITH LAST ANS NEXT MONTH LIKES IN PERCENTAGE 

SELECT *,
ROUND((likes - LAG(likes) OVER(PARTITION BY user_id ORDER BY post_date))* 100/
LAG(likes)OVER(PARTITION BY user_id ORDER BY post_date),1 ) AS GROWTH

FROM [dbo].[posts];

--HOW WAS THE FIRST ENGAGEMENT OF A CREATOR (FIRST VALUE OF LIKES,COMMENTS,SHARES)

SELECT *,  --FIRST_VALUE IS A WINDOW FUNCTION USED TO SEE THE START OF  SOMETHING 
FIRST_VALUE(likes+comments+shares) OVER ( PARTITION BY  user_id ORDER BY post_date) AS FIRST_ENGAGEMENT
FROM [dbo].[posts];

--LASTEST CREATOR ENGEAGEMENT (LAST VALUE OF LIKES,COMMENTS,SHARES)
---UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING IS USED TO COMPARE THE CURRENT PERFORMANCE WITH THE LATEST PERFORMANCE

SELECT *,
LAST_VALUE(likes+comments+shares) OVER (PARTITION BY user_id ORDER BY post_date
ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS LATEST_ENGAGEMENT
FROM [dbo].[posts];


--TOP 2 POSTS OF EACH MONTH ON BASIS OF ENGAGEMENT (LIKES+COMMENTS+SHARES)

WITH X AS (SELECT *,
ROW_NUMBER() OVER(PARTITION BY MONTH(post_date)ORDER BY likes+comments+shares DESC) AS RANKING 
FROM [dbo].[posts])

SELECT * FROM X 
WHERE RANKING<=2;

--DIVIDE CREATORS IN 4 QUARTILES BASED ON LIKES - THIS ENABLES  TO SEE THE PERFORMANCE OF CREATORS IN DIFFERENT QUARTILES AND IDENTIFY THE TOP PERFORMERS
SELECT *,
NTILE(4) OVER ( ORDER BY likes DESC) AS QUARTILE
FROM [dbo].[posts];

--CONTRIBUTION OF EACH POST TO THE OVERALL ENGAGEMENT OF A CREATOR (LIKES+COMMENTS+SHARES) - THIS HELPS TO UNDERSTAND THE IMPACT OF EACH POST ON THE CREATOR'S OVERALL PERFORMANCE

SELECT *,
CONCAT((likes+comments+shares) *100/ SUM(likes+comments+shares) OVER (PARTITION BY user_id) ,'%') AS CONTRIBUTION
FROM [dbo].[posts];


--
SELECT * FROM [dbo].[posts];
SELECT * FROM [dbo].[users];

--LEADERBOARD OF CREATORS BASED ON OVERALL ENGAGEMENT (LIKES+COMMENTS+SHARES) 
WITH X AS ( SELECT U.user_id,U.user_name,U.country,
 SUM(P.likes+P.comments+P.shares) AS ENGAGMENT

 FROM [dbo].[posts] P INNER JOIN [dbo].[users] U
 ON P.user_id =U.user_id

 GROUP BY U.user_id, U.user_name,U.country)

 SELECT *, DENSE_RANK () OVER ( ORDER BY ENGAGMENT DESC ) AS RANKING
 FROM X;

